#theme: jekyll-theme-leap-day
remote_theme: vicariousdrama/nodeyez
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  parse_block_html: true
title: NODEYEZ - Display panels to get the most from your Bitcoin node
description: Display panels and scripts to get the most from your Bitcoin node
url: https://nodeyez.com
#baseurl: /nodeyez
twitter_username: vicariousdrama
header_image: /images/nodeyez.svg
collections:
  developer:
    output: true
    permalink: /developer/:path
  docs:
    output: true
    permalink: /docs/:path
  install_steps:
    output: true
    permalink: /install_steps/:path
include: [".well-known"]
